server:
  port: 8090
spring.cloud.stream:
  function:
    definition : pageEventConsumer;pageEventSupplier;pageStreamConsumer;kStreamFunction
  bindings:
    pageEventConsumer-in-0:
      destination: R224
      group: G1
    pageEventSupplier-out-0:
      destination: R333
    kStreamFunction-in-0:
      destination: R333
      group: G44
    kStreamFunction-out-0:
      destination: R66
spring:
  kafka:
    streams:
      application-id: app2
    consumer:
      enable-auto-commit: true
      auto-offset-reset: earliest
